os: linux
dist: bionic
language: cpp

env:
    global:
        secure: "Xtwlf0NPrlw6NpdLV1iIgs1f8aWK5lqGmfg1iCDQrsuYhHl7/3tldUIS/I1YMyxPOQHRuaBhFPBgv7YMcDl/1Hss001xm3ILbtgDNBCzUG6v4ZgZsB3qUaWWTegw/y9UwQbjqD720on9Wpqr6Rr8XqjaBxn+siWRN5io/sQj6w2o74xn2/+rIol+ei/XLtdmMHoayO24xN1dAAv14/0kCqH1L7Atij33grjyFIF3M6fyVlZzruoBTQVLfq/J19lkHtCf6ItjC2f2gorXYgGBfNQaWYz00U/fIHUgtLo/7QtvNsofb+J39jOeG97I4P0Nwu+2Jhn3O1wU0pnnCl99qLpDbYrzch/TaRWVau3khjLG2/1twLImdJn4nWXeBuX5S4Kazr3s0hGF2wBfFPDQU9izg/3nxC6gIT+o+BJvLcdJsio3SDdN2KorEuQrteRJsGXSAgOebBnsDaVkiKy/QDj6V4ZDYdkZ9G5OwsAAGpfDLDkRRwquCW83zUNBicReYOpervdtIDBQg2KbNdb6lIR+5b16+uggeoFV1O/+2dfKYj5MqXwtSRGRwCZ5ArFjWN1ARI3pObjrutsX6PoZdYL6Y4d6UYm7koI+25dkY3GCPCY5KB09ory6zIQ7vvfSHOs4LZZqdS6jDVtCjgWscwwgqEjmOA5uWGYWmf+yDs8="

branches:
    only:
        - master

matrix:
  include:
    - name: "C++11 build"
      compiler: g++-8
      env:
        - ARCH=amd64
        #compiler
        - COMPILER=g++-8
        - ACXX=g++-8
        - ACC=gcc-8
        #build settings
        - build_type=Debug
        - SANITIZER=false
        - CXX_STANDARD=11
      addons:
        apt:
          packages: ['gcc-8', 'g++-8', 'cmake']

    - name: "C++14 build"
      compiler: g++-8
      env:
        - ARCH=amd64
        #compiler
        - COMPILER=g++-8
        - ACXX=g++-8
        - ACC=gcc-8
        #build settings
        - build_type=Release
        - SANITIZER=false
        - CXX_STANDARD=14
      addons:
        apt:
          packages: ['gcc-8', 'g++-8', 'cmake']

    - name: "C++17 build"
      compiler: g++-8
      env:
        - ARCH=amd64
        #compiler
        - COMPILER=g++-8
        - ACXX=g++-8
        - ACC=gcc-8
        #build settings
        - build_type=Release
        - SANITIZER=false
        - CXX_STANDARD=17
      addons:
        apt:
          packages: ['gcc-8', 'g++-8', 'cmake']

    - name: "address sanitizer build"
      if: branch = master AND false #disabled
      compiler: g++-8
      env:
        - ARCH=amd64
        #compiler
        - COMPILER=g++-8
        - ACXX=g++-8
        - ACC=gcc-8
        #build settings
        - build_type=Release
        - SANITIZER=true

    - name: "coverage build"
      if: branch = master
      compiler: g++-7
      env:
        - ARCH=amd64
        #compiler
        - COMPILER=g++-7
        - ACXX=g++-7
        - ACC=gcc-7
        #build settings
        - build_type=Debug
        - CXXFLAGS="-O0 --coverage"
        - coverage=true
      addons:
        apt:
          packages: ['gcc-7', 'g++-7', 'lcov', 'cmake']
      script:
        - ./scripts/travis-test.sh
        - ./scripts/travis-after-success.sh

    - name: "clang build"
      if: branch = master AND false # disabled because of clang ICE
      compiler: clang++-9
      env:
        - ARCH=amd64
        #compiler
        - COMPILER=clang++-9
        - ACXX=clang++-9
        - ACC=clang-9
        #build settings
        - build_type=Release
        - tests=ON
        - examples=ON
        - verbose=true
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages: ['clang-9', 'clang++-9', 'clang-format-9', 'clang-tools-9', 'cmake']


install:
    - export CXX=$ACXX
    - export CC=$ACC
    - export CXX_STANDARD=${CXX_STANDARD:-14}
    - export BUILD_TYPE=${build_type}
    - export COVERAGE=${coverage:-false}
    - cmake --version
    - $CXX --version

script: ./scripts/travis-test.sh
